### ISSUE TITLE
Fix R CMD CHECK note

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.modules.general#520]
```
* checking R code for possible problems ... NOTE
plot_var_summary: no visible binding for global variable ‘count’
Undefined global functions or variables:
  count
```

**Comment by donyunardi** [comment]
This is due to this line:
https://github.com/insightsengineering/teal.modules.general/blob/main/R/tm_variable_browser.R#L946

https://github.com/insightsengineering/teal.modules.general/blob/main/R/tm_variable_browser.R#L957

At the moment, it felt like a false positive for me because the ggplot2 syntax is correct.
Perhaps we can just move forward with `utils::globalVariables()` to suppress the NOTE.
