### ISSUE TITLE
Using report_card_template on tm_missing_data

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.modules.general#587]
Did we miss using the new function `report_card_template()` on `tm_missing_data`?

Related to this PR:
https://github.com/insightsengineering/teal.modules.general/pull/584/files

https://github.com/insightsengineering/teal.modules.general/blob/eef36c1dda918fcbebe948d8bef189bd7e545974/R/tm_missing_data.R#L1204

**Comment by kartikeyakirar** [comment]
The `report_card_template()` function was intentionally not employed in `tm_missing_data `because the report's structure did not precisely align with the defined template structure as outlined in the template definition at https://github.com/insightsengineering/teal/blob/main/R/utils.R#L65-L79.

In the template structure, if a label is detected, it serves as both the title and is added as header2 text. However, in this case, the header2 text contains information that should not be replaced by the label. Hence, `report_card_template()` was not used to prevent unintended overwriting of important header2 information.

**Comment by kartikeyakirar** [comment]
this can be closed

**Comment by m7pr** [comment]
yeah, card_fun in `tm_missing_data` contains `label` parameter

```r
 card_fun <- function(comment, label) {
```

so this allows to pass the label. The body is too complex to be used in `report_card_template()` as Kartik suggested. Closing this.

**Comment by donyunardi** [comment]
Thanks for the clarification @kartikeyakirar @m7pr !
