### ISSUE TITLE
replace `var_labels` with `teal.data::col_labels`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.general#658]
@insightsengineering/nest-core-dev 
`var_labels` (originally from `formatters`) was copied to several packages, including `teal.data`, where it was renamed to `col_labels` improved. In light of that, should `teal.modules.general` continue to use its copy of `var_labels` or rather switch to `teal.data::col_labels`?

It would require adding `teal.data` to `Imports`. ~~Currently `teal.data` is not a dependency (even though the package does rely on the `teal_data` class), we only use `eval_code` from `teal.code`.~~
_EDIT:_ `teal.data` was listed in `Suggests` but that was wrong and it is being moved to `Imports` in #643.

**Comment by m7pr** [comment]
I think it's better to have `var_labels` in one place where you control the development instead of having copies within multiple packages where you risk that one version will be different from another one. `teal.data` is not that big teal to be a dependency, because this package Depends on teal so I think it's OK. 

I know we were trying to remove `formatters` from dependencies some time ago and I think having a (improved) copy in `teal.data` and importing it from `teal.data` should be OK.

**Comment by chlebowa** [comment]
Done in https://github.com/insightsengineering/teal.modules.general/pull/673
